version: '2'
services:
    shopchallenge-app:
        image: shopchallenge
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://shopchallenge-mysql:3306/shopchallenge?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=shopchallenge-elasticsearch:9300
        ports:
            - 8081:8081
    shopchallenge-mysql:
        extends:
            file: mysql.yml
            service: shopchallenge-mysql
    shopchallenge-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: shopchallenge-elasticsearch
